#!/usr/bin/env bash
#Permanently have Ngnix redirect to another page
sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i '26s/^/        rewrite ^\/redirect_me\/ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n/' /etc/nginx/sites-available/default
sudo service nginx start
