#!/usr/bin/env bash
#Permanently have Ngnix redirect to another page
sudo apt-get update
sudo apt-get -y install nginx
sudo nginx -s start
sudo sed -i '26i\\trewrite ^/redirect_me www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;\n' /etc/nginx/sites-available/default
sudo nginx -s reload
