#!/usr/bin/env bash
#change user of nginx by changing ownership of nginx process
pkill apache2
sed -i "s/80 default/8080 default/g" /etc/nginx/sites-enabled/default
chmod 755 /etc/nginx/nginx.conf
chown -R nginx /var/log/nginx/ /etc/nginx/ /usr/share/nginx/
su nginx -c nginx
