#!/usr/bin/env bash
#change user of nginx by changing ownership of nginx process
pkill apache2
sed -i "s/80 default/8080 default/" /etc/nginx/sites-enabled/default
chmod 755 /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
su nginx -c service nginx start
