#!/usr/bin/env bash
#configure nginx with a custom http header
#install nginx on your web01 server
#Nginx should be listening on port 80
sudo apt-get update;
sudo apt-get install -y nginx;

file="/etc/nginx/sites-available/default"
#configure nginx with a custom http header
sudo sed -i "20i\\\t\t add_header X-Served-By: $HOSTNAME;" "$file"

sudo service nginx start;
