#!/usr/bin/env bash
# Configures Nginx so that its HTTP response contains a custom header
# customer header name must be X-Served-By
# custom header value must be hostname of the server Nginx is running on

# shellcheck disable=SC2154
# update apt-get and install nginx
sudo apt-get update;
sudo apt-get install -y nginx;
# create 404 page
echo "<h1>Ceci n'est pas une page</h1>" > test_file;
sudo mv test_file /usr/share/nginx/html/404.html;
# change 404 landing
new_string=" error_page 404 \/404.html;\n"
# setup redirect
file="/etc/nginx/sites-available/default"
sudo sed -i "26i $new_string" $file
new_string=" rewrite ^\/redirect_me https:\/\/www.espn.com\/ permanent;"
file="/etc/nginx/sites-available/default"
sudo sed -i "26i $new_string" $file

file="/etc/nginx/nginx.conf";
new_string="add_header X-Served-By $HOSTNAME";
sudo sed -i "22i $new_string;" $file
sudo service nginx start;
