#!/usr/bin/env bash
# installing the load balancer
sudo apt-get update
sudo apt-get install haproxy
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

file=/etc/haproxy/haproxy.cfg

sudo cp $file $file.copy

sudo sed -i -e '$a\listen appname 0.0.0.0:80\n\tmode http\n\tstats enable' $file
sudo sed -i -e '$a\\tbalance roundrobin\n\toption httpclose\n\toption forwardfor' $file
sudo sed -i -e '$a\\tserver 100-web-01 54.209.54.84:80\n\tserver 100-web-02 54.243.1.173:80' $file
sudo service haproxy start
