#!/usr/bin/env bash
#Bash script that displays Holberton School 10 times, but for the 9th iteration, also displays Hi.
i=1
while true; do
    echo "Holberton School"
    if (("$i" == 9)); then
	echo "Hi"
    elif (("$i" == 10)); then
	break
    fi

    ((i+=1))
done
