#!/usr/bin/env bash
# have nginx listen to port 80 by creating a symbolic into sites-available
sudo sed -i 's/8080 default/80 default/' /etc/nginx/sites-available/default  /etc/nginx/sites-enabled/default
sudo service nginx start
