#!/usr/bin/env bash
# have nginx listen to port 80 by creating a symbolic into sites-available
sed 's/status_of_proc -p $PID "$DAEMON" "$NAME"/ echo" * nginx is not running/' /etc/init.d/nginx
sed 's/8080/80/' /etc/nginx/sites-enable/default /etc/nginx/sites-available/default 
service nginx start
