#!/usr/bin/env bash
while IFS=: read -r f1 f2 f3 f4 f5 f6 f7; do
    echo "The user root is part of the \$f1 gang, lives in \$f6 and rides \$f7. \$f3 place is protected by the passcode \$f2, more info about the user here: \$f5"
done <  /etc/passwd
